### ISSUE TITLE
Able to place more than 3 ships

### ISSUE THREAD

**Issue by puppol** [cs361w2019-osu/sprint1-team-1#11]
When placing ships, you are not limited to three ships.

**Comment by duke9** [comment]
I think that only one of each type of ship should be placed. instead of just limiting the number of ships to 3

**Comment by duke9** [comment]
I think that there is a un ending loop created when you return false from placeShip, because placedShips in game.js is not updated every time a ship is placed. This causes the if else loop in cellClick() from game.js to never enter the else statement.
