### ISSUE TITLE
Be Able to Toggle Submerging When Placing Submarine

### ISSUE THREAD

**Issue by ashyan** [cs361w2019-osu/sprint1-team-1#95]
Currently, the submarine is always submerged when placed. We need to add an option to place it at the surface or underwater

**Comment by ahyork** [comment]
Submarines should always be placed as submerged, do we need this?

**Comment by ashyan** [comment]
No

> A new type of ship will be introduced: the submarine. A submarine can be placed on the surface or it can be submerged,
